version: '3.8'

services:
  web:
    container_name: editor.osb.im
    image: editor.osb.im:1.${BUILD_NUMBER}
    restart: always
    ports:
      - 9030:80
    networks:
      - npm

networks:
  npm:
    external:
      name: npm
