import {
	ClassicEditor as ClassicEditorBase,
	Essentials,
	Paragraph,
	BlockQuote,
	MediaEmbed,
	PasteFromOffice,
	Heading,
	Title,
	Font,
	Autoformat,
	Alignment,
	TextTransformation,
	PageBreak,
	LinkImage,
	Base64UploadAdapter,
	SourceEditing,
	CodeBlock,
	FindAndReplace,
	Highlight,
	HorizontalLine,
	SelectAll,
	RemoveFormat,
	HtmlEmbed,
	Markdown,
	WordCount,
	TextPartLanguage,
	Indent,
	IndentBlock,
	// table
	Table,
	TableToolbar,
	TableCaption,
	TableCellProperties,
	TableProperties,
	TableColumnResize,
	// special-characters
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	// html-support
	FullPage,
	HtmlComment,
	GeneralHtmlSupport,
	// basic-styles
	Bold,
	Code,
	Italic,
	Strikethrough,
	Subscript,
	Superscript,
	Underline,
	// image
	Image,
	ImageInsert,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageResize,
	ImageUpload,
	AutoImage,
	List,
	ListProperties,
} from "ckeditor5"
import CustomList from "@/features/ckeditor/model/custom-list/index.js";

import "ckeditor5/ckeditor5.css";

export default class ClassicEditor extends ClassicEditorBase {}

ClassicEditor.builtinPlugins = [
	Essentials,
	Paragraph,
	BlockQuote,
	MediaEmbed,
	PasteFromOffice,
	Heading,
	Title,
	Font,
	Autoformat,
	Alignment,
	TextTransformation,
	PageBreak,
	LinkImage,
	Base64UploadAdapter,
	SourceEditing,
	CodeBlock,
	FindAndReplace,
	Highlight,
	HorizontalLine,
	SelectAll,
	RemoveFormat,
	HtmlEmbed,
	Markdown,
	WordCount,
	TextPartLanguage,
	Indent,
	IndentBlock,
	// table
	Table,
	TableToolbar,
	TableCaption,
	TableCellProperties,
	TableProperties,
	TableColumnResize,
	// special-characters
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	// html-support
	FullPage,
	HtmlComment,
	GeneralHtmlSupport,
	// basic-styles
	Bold,
	Code,
	Italic,
	Strikethrough,
	Subscript,
	Superscript,
	Underline,
	// image
	Image,
	ImageInsert,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageResize,
	ImageUpload,
	AutoImage,
	// list
	List,
	ListProperties,
	CustomList,
];

ClassicEditor.defaultConfig = {
	toolbar: {
		language: "en",
		items: [
			"undo",
			"redo",
			"|",
			// "sourceEditing",
			"heading",
			"|",
			"bold",
			"italic",
			"underline",
			"strikethrough",
			"|",
			"fontSize",
			"fontColor",
			"fontBackgroundColor",
			"|",
			"alignment",
			"bulletedList",
			"numberedList",
			"outdent",
			"indent",
			"blockQuote",
			"|",
			"insertTable",
			// "imageUpload",
			// "mediaEmbed",
			"|",
			"pageBreak",
		]
	},
	codeBlock: {
		languages: [
			{ language: "plaintext", label: "Plain text" }, // The default language.
			{ language: "c", label: "C" },
			{ language: "cs", label: "C#" },
			{ language: "cpp", label: "C++" },
			{ language: "css", label: "CSS" },
			{ language: "diff", label: "Diff" },
			{ language: "html", label: "HTML" },
			{ language: "java", label: "Java" },
			{ language: "javascript", label: "JavaScript" },
			{ language: "php", label: "PHP" },
			{ language: "python", label: "Python" },
			{ language: "ruby", label: "Ruby" },
			{ language: "typescript", label: "TypeScript" },
			{ language: "xml", label: "XML" },
		],
	},
	heading: {
		options: [
			{ model: "paragraph", title: "Paragraph", class: "ck-heading_paragraph" },
			{
				model: "heading1",
				view: "h1",
				title: "Heading 1",
				class: "ck-heading_heading1",
			},
			{
				model: "heading2",
				view: "h2",
				title: "Heading 2",
				class: "ck-heading_heading2",
			},
			{
				model: "heading3",
				view: "h3",
				title: "Heading 3",
				class: "ck-heading_heading3",
			},
			{
				model: "heading4",
				view: "h4",
				title: "Heading 4",
				class: "ck-heading_heading4",
			},
			{
				model: "heading5",
				view: "h5",
				title: "Heading 5",
				class: "ck-heading_heading5",
			},
			{
				model: "heading6",
				view: "h6",
				title: "Heading 6",
				class: "ck-heading_heading6",
			},
		],
	},
	htmlSupport: {
		allow: [
			{
				name: /.*/,
				attributes: true,
				classes: true,
				styles: true,
			},
		],
	},
	fontSize: {
		options: [
			9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 25, 27, 29, 31, 33,
			35,
		],
	},
	extraAllowedContent: '*[*]{*}',
	fontFamily: {
		supportAllValues: true,
	},
	list: {
		properties: {
			styles: true,
			startIndex: true,
			reversed: true
		}
	},
	alignment: {
		options: ["justify", "left", "center", "right"],
	},
	table: {
		contentToolbar: [
			"tableColumn", "tableRow",
			"|", "mergeTableCells",
			"|", "tableCellProperties", "tableProperties",
			"|", "toggleTableCaption",
		],
	},
	image: {
		resizeUnit: "%",
		toolbar: [
			"dtmCreateContextMenu", "dtmEditContextMenu", "dtmDeleteContextMenu", "imageTextAlternative", "toggleImageCaption",
			"|", "imageStyle:alignLeft", "imageStyle:alignCenter", "imageStyle:alignRight",
			"|", "imageStyle:alignBlockLeft", "imageStyle:block", "imageStyle:alignBlockRight",
			"|", { items: ["imageStyle:side", "imageStyle:inline"], defaultItem: "imageStyle:side", },
			"|", "linkImage", "resizeImage",
		],
		resizeOptions: [
			{
				name: "resizeImage:original",
				value: null,
				label: "Original",
			},
			{
				name: "resizeImage:25",
				value: "25",
				label: "25%",
			},
			{
				name: "resizeImage:50",
				value: "50",
				label: "50%",
			},
			{
				name: "resizeImage:75",
				value: "75",
				label: "75%",
			},
		],
		styles: ["full", "alignLeft", "alignRight"],
	},
	typing: {
		transformations: {
			includes: ["quotes", "typography", "mathematical", "symbols"],
		},
	},
	htmlEmbed: {
		showPreviews: true,
	},
};
