export default {
	toolbar: {
		items: [
			"undo",
			"redo",
			"|",
			// TODO: Add "find and replace" to the toolbar
			// "findAndReplace",
			// "selectAll",
			"heading",
			"|",
			"bold",
			"italic",
			"underline",
			"strikethrough",
			"|",
			"fontFamily",
			"fontSize",
			"fontColor",
			"fontBackgroundColor",
			"highlight",
			"|",
			"textPartLanguage",
			// TODO: Add "text group component" to the toolbar
			// "|",
			// {
			//   name: "textStyle",
			//   items: [
			//     "bold",
			//     "italic",
			//     "underline",
			//     "strikethrough",
			//     "fontFamily",
			//     "fontSize",
			//     "fontColor",
			//     "fontBackgroundColor",
			//     "highlight",
			//     "heading",
			//     "textPartLanguage",
			//   ],
			//   label: "Text Styles",
			//   icon: "text",
			// },
			"|",
			"alignment",
			"outdent",
			"indent",
			"bulletedList",
			"numberedList",
			"blockQuote",
			"|",
			"insertImage",
			"insertTable",
			"link",
			"specialCharacters",
			"horizontalLine",
			"|",
			"pageBreak",
			// "codeBlock",
			// "htmlEmbed",
			"|",
			"subscript",
			"superscript",
			"removeFormat",
			// "|",
			// "sourceEditing",
			// "|",
			// "textPartLanguage",
		],
	},
	heading: {
		options: [
			{
				model: "paragraph",
				title: "Paragraph",
				class: "ck-heading_paragraph",
			} as const,
			{
				model: "heading1",
				view: "h1",
				title: "Heading 1",
				class: "ck-heading_heading1",
			} as const,
			{
				model: "heading2",
				view: "h2",
				title: "Heading 2",
				class: "ck-heading_heading2",
			} as const,
			{
				model: "heading3",
				view: "h3",
				title: "Heading 3",
				class: "ck-heading_heading3",
			} as const,
			{
				model: "heading4",
				view: "h4",
				title: "Heading 4",
				class: "ck-heading_heading4",
			} as const,
			{
				model: "heading5",
				view: "h5",
				title: "Heading 5",
				class: "ck-heading_heading5",
			} as const,
			{
				model: "heading6",
				view: "h6",
				title: "Heading 6",
				class: "ck-heading_heading6",
			} as const,
		],
	},
	codeBlock: {
		languages: [
			{ language: "plaintext", label: "Plain text" }, // The default language.
			{ language: "c", label: "C" },
			{ language: "cs", label: "C#" },
			{ language: "cpp", label: "C++" },
			{ language: "css", label: "CSS" },
			{ language: "diff", label: "Diff" },
			{ language: "html", label: "HTML" },
			{ language: "java", label: "Java" },
			{ language: "javascript", label: "JavaScript" },
			{ language: "php", label: "PHP" },
			{ language: "python", label: "Python" },
			{ language: "ruby", label: "Ruby" },
			{ language: "typescript", label: "TypeScript" },
			{ language: "xml", label: "XML" },
		],
	},
	htmlSupport: {
		allow: [
			{
				name: /.*/,
				attributes: true as const,
				classes: true as const,
				styles: true as const,
			},
		],
	},
	htmlEmbed: {
		showPreviews: true,
	},
	extraAllowedContent: "*[*]{*}",
	fontSize: {
		options: [
			9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 25, 27, 29, 31, 33,
		],
	},
	fontFamily: {
		supportAllValues: true,
	},
	list: {
		properties: {
			styles: true,
			startIndex: true,
			reversed: true,
		},
	},
	table: {
		contentToolbar: [
			"tableColumn",
			"tableRow",
			"|",
			"mergeTableCells",
			"|",
			"tableCellProperties",
			"tableProperties",
			"|",
			"toggleTableCaption",
		],
	},
	image: {
		toolbar: [
			"imageStyle:alignLeft",
			"imageStyle:alignCenter",
			"imageStyle:alignRight",
			"|",
			"imageStyle:alignBlockLeft",
			"imageStyle:block",
			"imageStyle:alignBlockRight",
			"|",
			{
				name: "imageStyle",
				items: ["imageStyle:side", "imageStyle:inline"],
				defaultItem: "imageStyle:side",
			},
			"|",
			"linkImage",
			"resizeImage",
		],
		resizeOptions: [
			{
				name: "resizeImage:original",
				value: null,
				label: "Original",
			},
			{
				name: "resizeImage:25",
				value: "25",
				label: "25%",
			},
			{
				name: "resizeImage:50",
				value: "50",
				label: "50%",
			},
			{
				name: "resizeImage:75",
				value: "75",
				label: "75%",
			},
		],
	},
	typing: {
		transformations: {
			include: ["quotes", "typography", "mathematical", "symbols"],
		},
	},
};
